# Generated by Django 2.0.4 on 2018-05-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illustration', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
