# Generated by Django 2.0.4 on 2018-05-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illustration', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsFlash',
        ),
    ]
