# Generated by Django 2.0.4 on 2018-05-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustration', '0006_delete_newsflash'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsFlash',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('datetime', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
